// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @react-native-async-storage/async-storage
#include <winrt/ReactNativeAsyncStorage.h>

// Includes from @react-native-community/slider
#include <winrt/SliderWindows.h>

// Includes from react-native-linear-gradient
#include <winrt/BVLinearGradient.h>

// Includes from react-native-track-player
#include <winrt/RNTrackPlayer.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @react-native-async-storage/async-storage
    packageProviders.Append(winrt::ReactNativeAsyncStorage::ReactPackageProvider());
    // IReactPackageProviders from @react-native-community/slider
    packageProviders.Append(winrt::SliderWindows::ReactPackageProvider());
    // IReactPackageProviders from react-native-linear-gradient
    packageProviders.Append(winrt::BVLinearGradient::ReactPackageProvider());
    // IReactPackageProviders from react-native-track-player
    packageProviders.Append(winrt::RNTrackPlayer::ReactPackageProvider());
}

}
